FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY backend/ ./backend/
COPY .env.example .env
EXPOSE 5000
CMD ["python", "-m", "backend.app"]
