/**
 * Demo data — used when backend is unavailable.
 * Owner: Sara
 */
export const DEMO_LISTINGS = [
  { id:"listing_001", address:"742 Everglade Ave, Santa Clara",     lat:37.3541, lng:-121.9552,
    household_name:"Chen Family",        total_value:8.75,  total_lbs:23.3, status:"available",
    notes:"Near garage door",
    materials:[{type:"cardboard",lbs:18,value:0.72},{type:"aluminum_cans",lbs:3.2,value:5.28},{type:"plastic_pet",lbs:2.1,value:2.75}]},
  { id:"listing_002", address:"1208 Kiely Blvd, Santa Clara",       lat:37.3498, lng:-121.9621,
    household_name:"Rivera Household",   total_value:13.42, total_lbs:24.5, status:"available",
    notes:"Old laptop + router",
    materials:[{type:"ewaste_noncrt",lbs:8.5,value:9.86},{type:"cardboard",lbs:12,value:0.48}]},
  { id:"listing_003", address:"3301 Pruneridge Ave, Santa Clara",   lat:37.3612, lng:-121.9789,
    household_name:"Park Residence",     total_value:13.57, total_lbs:21.5, status:"available",
    notes:"Old wiring + scrap",
    materials:[{type:"copper_wire",lbs:2.5,value:9.63},{type:"scrap_metal_mixed",lbs:11.0,value:3.30}]},
  { id:"listing_004", address:"985 Homestead Rd, Sunnyvale",        lat:37.3688, lng:-122.0141,
    household_name:"Nguyen Family",      total_value:17.26, total_lbs:24.0, status:"available",
    notes:"Party cleanup",
    materials:[{type:"aluminum_cans",lbs:8.5,value:14.03},{type:"glass_bottles",lbs:12.0,value:1.20}]},
  { id:"listing_005", address:"2187 Monroe St, Santa Clara",        lat:37.3449, lng:-121.9701,
    household_name:"Thompson Residence", total_value:48.61, total_lbs:41.0, status:"available",
    notes:"2 CRT TVs + tablets. Heavy!",
    materials:[{type:"ewaste_crt",lbs:35.0,value:41.65},{type:"ewaste_noncrt",lbs:6.0,value:6.96}]},
  { id:"listing_006", address:"4421 Stevens Creek Blvd, San Jose",  lat:37.3229, lng:-121.9876,
    household_name:"Garcia Family",      total_value:7.94,  total_lbs:57.5, status:"available",
    notes:"Moving boxes",
    materials:[{type:"cardboard",lbs:45.0,value:1.80},{type:"newspaper",lbs:8.0,value:0.24}]},
  { id:"listing_007", address:"671 Pastoria Ave, Sunnyvale",        lat:37.3751, lng:-122.0052,
    household_name:"Kim Household",      total_value:25.43, total_lbs:14.7, status:"available",
    notes:"Workshop cleanout",
    materials:[{type:"copper_wire",lbs:4.2,value:16.17},{type:"scrap_aluminum",lbs:7.5,value:5.78}]},
  { id:"listing_008", address:"1833 Benton St, Santa Clara",        lat:37.3578, lng:-121.9834,
    household_name:"Patel Family",       total_value:14.21, total_lbs:26.5, status:"available",
    notes:"Weekly recyclables",
    materials:[{type:"aluminum_cans",lbs:5.5,value:9.08},{type:"plastic_pet",lbs:3.0,value:3.93}]},
  { id:"listing_009", address:"905 Lawrence Expy, Sunnyvale",       lat:37.3821, lng:-121.9945,
    household_name:"Wilson Residence",   total_value:12.52, total_lbs:44.5, status:"available",
    notes:"Old BBQ + fence posts",
    materials:[{type:"steel_iron",lbs:28.0,value:2.24},{type:"scrap_metal_mixed",lbs:15.0,value:4.50}]},
  { id:"listing_010", address:"2244 El Camino Real, Santa Clara",   lat:37.3501, lng:-122.0012,
    household_name:"Anderson Family",    total_value:33.57, total_lbs:28.5, status:"available",
    notes:"5 old laptops",
    materials:[{type:"ewaste_noncrt",lbs:22.0,value:25.52},{type:"aluminum_cans",lbs:4.0,value:6.60}]},
  { id:"listing_011", address:"3788 Lochinvar Ave, Santa Clara",    lat:37.3634, lng:-121.9667,
    household_name:"Martinez Family",    total_value:12.29, total_lbs:48.5, status:"available",
    notes:"Garage cleanout",
    materials:[{type:"cardboard",lbs:30.0,value:1.20},{type:"aluminum_cans",lbs:6.5,value:10.73}]},
  { id:"listing_012", address:"559 Showers Dr, Mountain View",      lat:37.3989, lng:-122.0820,
    household_name:"Lee Household",      total_value:46.27, total_lbs:29.0, status:"available",
    notes:"Solar wiring + servers",
    materials:[{type:"copper_wire",lbs:6.0,value:23.10},{type:"ewaste_noncrt",lbs:14.0,value:16.24}]},
  { id:"listing_013", address:"1102 Saratoga Ave, San Jose",        lat:37.3145, lng:-121.9567,
    household_name:"Johnson Family",     total_value:15.19, total_lbs:31.0, status:"available",
    notes:"Very sorted already",
    materials:[{type:"glass_bottles",lbs:22.0,value:2.20},{type:"plastic_pet",lbs:5.5,value:7.21}]},
  { id:"listing_014", address:"447 N Winchester Blvd, Santa Clara", lat:37.3712, lng:-121.9523,
    household_name:"Davis Residence",    total_value:63.32, total_lbs:70.0, status:"available",
    notes:"3 large CRT TVs. Very heavy.",
    materials:[{type:"ewaste_crt",lbs:52.0,value:61.88},{type:"steel_iron",lbs:18.0,value:1.44}]},
  { id:"listing_015", address:"2890 Moorpark Ave, San Jose",        lat:37.3301, lng:-121.9712,
    household_name:"Hernandez Family",   total_value:29.13, total_lbs:41.0, status:"available",
    notes:"Big family accumulation",
    materials:[{type:"aluminum_cans",lbs:11.0,value:18.15},{type:"plastic_pet",lbs:6.0,value:7.86}]},

  // Small businesses (opt-in partners) - heavier loads, fewer stops.
  { id:"listing_016", address:"2525 Augustine Dr, Santa Clara",     lat:37.3732, lng:-121.9828,
    household_name:"Mailroom Partner (Business)", listing_kind:"business", total_value:14.60, total_lbs:380.0, status:"available",
    notes:"Flattened boxes behind loading dock (8-11am)",
    materials:[{type:"cardboard",lbs:320.0,value:12.80},{type:"newspaper",lbs:60.0,value:1.80}]},
  { id:"listing_017", address:"1111 Morse Ave, Sunnyvale",          lat:37.3877, lng:-122.0176,
    household_name:"Retail Stockroom (Business)", listing_kind:"business", total_value:18.00, total_lbs:460.0, status:"available",
    notes:"Pallet of broken-down boxes, ready to load",
    materials:[{type:"cardboard",lbs:420.0,value:16.80},{type:"newspaper",lbs:40.0,value:1.20}]},
  { id:"listing_018", address:"99 S Market St, San Jose",           lat:37.3346, lng:-121.8916,
    household_name:"Event Venue Cleanup (Business)", listing_kind:"business", total_value:44.60, total_lbs:73.0, status:"available",
    notes:"Weekend event leftovers (sorted bags)",
    materials:[{type:"aluminum_cans",lbs:18.0,value:29.70},{type:"plastic_pet",lbs:10.0,value:13.10},{type:"cardboard",lbs:45.0,value:1.80}]},
  { id:"listing_019", address:"700 Lawrence Expy, Santa Clara",     lat:37.3681, lng:-121.9952,
    household_name:"Hardware Shop (Business)", listing_kind:"business", total_value:22.50, total_lbs:215.0, status:"available",
    notes:"Old shelving + packaging (tie-down needed)",
    materials:[{type:"scrap_metal_mixed",lbs:35.0,value:10.50},{type:"steel_iron",lbs:120.0,value:9.60},{type:"cardboard",lbs:60.0,value:2.40}]},
  { id:"listing_020", address:"3250 Scott Blvd, Santa Clara",       lat:37.3756, lng:-121.9727,
    household_name:"Cafe + Roastery (Business)", listing_kind:"business", total_value:10.20, total_lbs:228.0, status:"available",
    notes:"Back alley bins, clean/dry only",
    materials:[{type:"cardboard",lbs:210.0,value:8.40},{type:"glass_bottles",lbs:18.0,value:1.80}]},
];

export const MATERIAL_RATES = {
  cardboard:         { rate: 0.04,  label: "Cardboard (OCC)",          emoji: "📦" },
  aluminum_cans:     { rate: 1.65,  label: "Aluminum Cans (CRV)",      emoji: "🥫" },
  plastic_pet:       { rate: 1.31,  label: "Clear PET Plastic (CRV)",  emoji: "🍶" },
  plastic_hdpe:      { rate: 0.58,  label: "HDPE Plastic (CRV)",       emoji: "🧴" },
  glass_bottles:     { rate: 0.10,  label: "Glass Bottles (CRV)",      emoji: "🍾" },
  copper_wire:       { rate: 3.85,  label: "Copper Wire",              emoji: "🔌" },
  scrap_aluminum:    { rate: 0.77,  label: "Scrap Aluminum",           emoji: "🔩" },
  ewaste_noncrt:     { rate: 1.16,  label: "E-Waste (Non-CRT)",        emoji: "💻" },
  ewaste_crt:        { rate: 1.19,  label: "E-Waste (CRT TV/Monitor)", emoji: "📺" },
  steel_iron:        { rate: 0.08,  label: "Steel / Iron",             emoji: "⚙️" },
  newspaper:         { rate: 0.03,  label: "Newspaper / Mixed Paper",  emoji: "📰" },
  scrap_metal_mixed: { rate: 0.30,  label: "Mixed Scrap Metal",        emoji: "🔧" },
};

export const DEMO_CLASSIFICATION = {
  success: true, source: "demo",
  materials: [
    { type: "cardboard",     label: "Cardboard (OCC)",        emoji: "📦", lbs: 14.0, rate: 0.04, value: 0.56, confidence: 0.91 },
    { type: "aluminum_cans", label: "Aluminum Cans (CRV)",    emoji: "🥫", lbs: 3.5,  rate: 1.65, value: 5.78, confidence: 0.87 },
    { type: "plastic_pet",   label: "Clear PET Plastic (CRV)",emoji: "🍶", lbs: 2.0,  rate: 1.31, value: 2.62, confidence: 0.79 },
  ],
  total_value: 8.96, total_lbs: 19.5,
  notes: "Demo mode — add AMD_API_KEY to backend/.env for live detection",
};
